# Generated by Django 4.1.7 on 2023-02-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_submission_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='daily_subm_limit',
            field=models.IntegerField(default=2),
        ),
    ]
