# Generated by Django 4.1.6 on 2023-02-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_submission_answeritems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerItems',
            new_name='AnswerItem',
        ),
    ]
