# Generated by Django 4.1.7 on 2023-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_daily_subm_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='daily_subm_limit',
        ),
        migrations.AddField(
            model_name='quiz',
            name='daily_subm_limit',
            field=models.IntegerField(default=2),
        ),
    ]
