# Generated by Django 4.1.6 on 2023-02-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_rename_answeritems_answeritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
